# Generated by Django 4.1.3 on 2022-12-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhakti_sadhna_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='punch_out',
        ),
        migrations.AlterField(
            model_name='attendence',
            name='attendence_status',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='ankit', max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='kushwaha', max_length=25),
        ),
    ]
