# Generated by Django 4.1.3 on 2022-11-26 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bhakti_sadhna_api', '0002_task_alter_user_managers_user_mobile_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
