# Generated by Django 4.1.3 on 2022-11-26 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bhakti_sadhna_api', '0004_alter_attendence_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique_for_date='date'),
        ),
    ]
