# Generated by Django 4.1.3 on 2022-11-26 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bhakti_sadhna_api', '0005_alter_attendence_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='attendence_status',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('N', 'Pending')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique_for_date='date'),
        ),
    ]
